import { SAMPLE_CAKE_IMAGES } from './mock-data';

export interface CakeShop {
  id: number;
  name: string;
  latitude: number;
  longitude: number;
  thumbnail: string;
  rating: number;
  reviewCount: number;
  categories: string[];
  address: string;
  gu: string;
}

export const CAKE_SHOPS: CakeShop[] = [
  {
    id: 1,
    name: 'Creamy Seoul',
    latitude: 37.4996,
    longitude: 127.0276,
    thumbnail: SAMPLE_CAKE_IMAGES[0],
    rating: 4.9,
    reviewCount: 156,
    categories: ['Y2K 감성', '레터링', '당일픽업'],
    address: '강남구 역삼동 123',
    gu: '강남구',
  },
  {
    id: 2,
    name: 'BlueDream Cakes',
    latitude: 37.5446,
    longitude: 127.0564,
    thumbnail: SAMPLE_CAKE_IMAGES[1],
    rating: 5.0,
    reviewCount: 234,
    categories: ['레터링', '3단케이크'],
    address: '성동구 성수동 456',
    gu: '성동구',
  },
  {
    id: 3,
    name: 'Rainbow Bakery',
    latitude: 37.5663,
    longitude: 126.9235,
    thumbnail: SAMPLE_CAKE_IMAGES[2],
    rating: 4.8,
    reviewCount: 98,
    categories: ['캐릭터', '도시락케이크'],
    address: '마포구 연남동 78',
    gu: '마포구',
  },
  {
    id: 4,
    name: 'FlowerCake Garden',
    latitude: 37.5172,
    longitude: 127.0473,
    thumbnail: SAMPLE_CAKE_IMAGES[3],
    rating: 4.8,
    reviewCount: 201,
    categories: ['플라워', '웨딩케이크'],
    address: '강남구 압구정동 22',
    gu: '강남구',
  },
  {
    id: 5,
    name: 'Sugar & Spice',
    latitude: 37.5222,
    longitude: 127.0543,
    thumbnail: SAMPLE_CAKE_IMAGES[4],
    rating: 4.7,
    reviewCount: 87,
    categories: ['레터링', '당일픽업', 'Y2K 감성'],
    address: '강남구 청담동 55',
    gu: '강남구',
  },
  {
    id: 6,
    name: 'Petit Four',
    latitude: 37.5571,
    longitude: 126.9253,
    thumbnail: SAMPLE_CAKE_IMAGES[5],
    rating: 4.9,
    reviewCount: 312,
    categories: ['프랑스식', '디저트'],
    address: '마포구 홍대앞 88',
    gu: '마포구',
  },
  {
    id: 7,
    name: 'Mellow Bakes',
    latitude: 37.5498,
    longitude: 126.9140,
    thumbnail: SAMPLE_CAKE_IMAGES[0],
    rating: 4.6,
    reviewCount: 64,
    categories: ['캐릭터', '레터링'],
    address: '마포구 합정동 30',
    gu: '마포구',
  },
  {
    id: 8,
    name: 'Cloud Nine Cakes',
    latitude: 37.5041,
    longitude: 127.0051,
    thumbnail: SAMPLE_CAKE_IMAGES[1],
    rating: 4.9,
    reviewCount: 188,
    categories: ['3단케이크', '웨딩케이크'],
    address: '서초구 반포동 14',
    gu: '서초구',
  },
  {
    id: 9,
    name: 'Pastel & Crumbs',
    latitude: 37.4917,
    longitude: 127.0124,
    thumbnail: SAMPLE_CAKE_IMAGES[2],
    rating: 4.7,
    reviewCount: 143,
    categories: ['Y2K 감성', '플라워'],
    address: '서초구 서초동 201',
    gu: '서초구',
  },
  {
    id: 10,
    name: 'Dear Cake',
    latitude: 37.5404,
    longitude: 127.0696,
    thumbnail: SAMPLE_CAKE_IMAGES[3],
    rating: 4.8,
    reviewCount: 176,
    categories: ['레터링', '도시락케이크', '당일픽업'],
    address: '광진구 건대입구 7',
    gu: '광진구',
  },
  {
    id: 11,
    name: 'Butter & Bloom',
    latitude: 37.5345,
    longitude: 126.9940,
    thumbnail: SAMPLE_CAKE_IMAGES[4],
    rating: 4.9,
    reviewCount: 259,
    categories: ['플라워', '레터링'],
    address: '용산구 이태원동 112',
    gu: '용산구',
  },
  {
    id: 12,
    name: 'Vanilla Moon',
    latitude: 37.5368,
    longitude: 127.0033,
    thumbnail: SAMPLE_CAKE_IMAGES[5],
    rating: 4.6,
    reviewCount: 73,
    categories: ['캐릭터', '도시락케이크'],
    address: '용산구 한남동 44',
    gu: '용산구',
  },
  {
    id: 13,
    name: 'Whisk & Wonder',
    latitude: 37.5822,
    longitude: 127.0016,
    thumbnail: SAMPLE_CAKE_IMAGES[0],
    rating: 4.7,
    reviewCount: 118,
    categories: ['레터링', 'Y2K 감성', '당일픽업'],
    address: '종로구 혜화동 35',
    gu: '종로구',
  },
  {
    id: 14,
    name: 'Blossom Bakehouse',
    latitude: 37.5735,
    longitude: 126.9851,
    thumbnail: SAMPLE_CAKE_IMAGES[1],
    rating: 4.8,
    reviewCount: 92,
    categories: ['플라워', '3단케이크'],
    address: '종로구 인사동 9',
    gu: '종로구',
  },
  {
    id: 15,
    name: 'Crème & Craft',
    latitude: 37.5635,
    longitude: 126.9826,
    thumbnail: SAMPLE_CAKE_IMAGES[2],
    rating: 5.0,
    reviewCount: 407,
    categories: ['레터링', '웨딩케이크', '3단케이크'],
    address: '중구 명동 100',
    gu: '중구',
  },
  {
    id: 16,
    name: 'Pink Sugar Cakes',
    latitude: 37.5262,
    longitude: 126.8748,
    thumbnail: SAMPLE_CAKE_IMAGES[3],
    rating: 4.7,
    reviewCount: 131,
    categories: ['캐릭터', 'Y2K 감성'],
    address: '양천구 목동 222',
    gu: '양천구',
  },
  {
    id: 17,
    name: 'Frosting & Co',
    latitude: 37.5219,
    longitude: 126.9244,
    thumbnail: SAMPLE_CAKE_IMAGES[4],
    rating: 4.8,
    reviewCount: 167,
    categories: ['레터링', '플라워', '당일픽업'],
    address: '영등포구 여의도동 66',
    gu: '영등포구',
  },
  {
    id: 18,
    name: 'Lemon Velvet',
    latitude: 37.6346,
    longitude: 127.0685,
    thumbnail: SAMPLE_CAKE_IMAGES[5],
    rating: 4.6,
    reviewCount: 54,
    categories: ['도시락케이크', '캐릭터'],
    address: '노원구 중계동 88',
    gu: '노원구',
  },
  {
    id: 19,
    name: 'Hazel & Honey',
    latitude: 37.6382,
    longitude: 127.0254,
    thumbnail: SAMPLE_CAKE_IMAGES[0],
    rating: 4.7,
    reviewCount: 89,
    categories: ['레터링', 'Y2K 감성'],
    address: '강북구 수유동 55',
    gu: '강북구',
  },
  {
    id: 20,
    name: 'Sparkle Cake Studio',
    latitude: 37.5108,
    longitude: 127.0869,
    thumbnail: SAMPLE_CAKE_IMAGES[1],
    rating: 4.9,
    reviewCount: 298,
    categories: ['3단케이크', '웨딩케이크', '플라워'],
    address: '송파구 잠실동 77',
    gu: '송파구',
  },
];
